# Generated by Django 2.0.2 on 2018-02-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCurso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CursoAlumno',
            fields=[
                ('idCA', models.IntegerField(primary_key=True, serialize=False)),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Curso')),
                ('rutAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='CursoPruebaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('idCursoAlumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crud.CursoAlumno')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('idPrueba', models.IntegerField(primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=25)),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crud.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='cursopruebaalumno',
            name='idPrueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crud.Prueba'),
        ),
        migrations.AddField(
            model_name='curso',
            name='rutProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crud.Profesor'),
        ),
    ]
